// POST /api/generate
// Body: { prompt: string }
// Uses Gemini image generation to create a character turnaround sheet
// (front view + back view of the same monster) on a white background.
// The frontend removes the white background and splits the two views.

const MODEL = 'gemini-2.5-flash-image';

const buildPrompt = (description) => `You are a professional character designer creating an original fantasy monster for children.

The input may include:
- A child's drawing.
- A child's spoken description.
- A structured monster description generated by AI.

Your task is to create a CHARACTER TURNAROUND SHEET of the EXACT SAME monster.

Requirements:
- Generate ONE image containing TWO full-body views of the same monster.
- Place the FRONT VIEW on the left.
- Place the BACK VIEW on the right.
- Both views must represent the EXACT SAME character.

Character consistency is critical:
- Use identical anatomy.
- Use identical proportions.
- Use identical colors.
- Use identical markings and patterns.
- Use identical horns, ears, wings, tails, accessories, and other features.
- Preserve all unique details.
- The back view must accurately show how the character looks from behind.

Visual style:
- Cute and appealing for children aged 5-12.
- Original fantasy monster design.
- Inspired by creature-collecting game aesthetics.
- Bright and cheerful colors.
- Clean sticker illustration style.
- High readability and strong silhouette.
- Full body visible from head to toe.
- Centered composition.

Output requirements:
- Plain solid pure white background (#FFFFFF), nothing else in the scene.
- Clean sticker-style edges suitable for cutting into stickers.
- No shadows extending outside the character.
- No floor, environment, scenery, props, or background elements.
- No text, labels, arrows, measurement lines, or character sheet annotations.
- Do not include the words "Front" or "Back".
- Keep sufficient spacing between the two views so they can be cropped into separate images later.

Safety requirements:
- Create an ORIGINAL design.
- Do NOT reproduce copyrighted characters.
- Avoid direct resemblance to existing monster franchises.

Monster description:

${description}`;

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY is not configured' });
  }

  const { prompt } = req.body || {};
  if (!prompt) {
    return res.status(400).json({ error: 'Missing prompt' });
  }

  try {
    const r = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: buildPrompt(prompt) }] }],
          generationConfig: {
            responseModalities: ['TEXT', 'IMAGE']
          }
        })
      }
    );

    if (!r.ok) {
      const detail = await r.text();
      console.error('Gemini generate error:', detail);
      return res.status(502).json({ error: 'Image generation failed' });
    }

    const data = await r.json();
    const parts = data?.candidates?.[0]?.content?.parts || [];
    const imagePart = parts.find((p) => p.inlineData?.data);
    if (!imagePart) {
      return res.status(502).json({ error: 'No image in AI response' });
    }

    return res.status(200).json({
      imageBase64: imagePart.inlineData.data,
      mimeType: imagePart.inlineData.mimeType || 'image/png'
    });
  } catch (err) {
    console.error('generate error:', err);
    return res.status(500).json({ error: 'Internal error' });
  }
}
